namespace CodeGenerator.Common
{
    public static class TsType
    {
        public const string Number = "number";
        public const string Boolean = "boolean";
        public const string String = "string";
        public const string Any = "any";
    }

    public static class FileContent
    {
        public const string HeaderNotes = @"//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated with cs-generation.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------";
    }
}
