name: Build and Test

on:
  pull_request:
    types:
      - opened
    branches:
      - main

env: 
  CSPROJ: CodeGenerator/CodeGenerator.csproj

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      
      - name: Install dependencies
        run: dotnet restore ${{ env.CSPROJ }}

      - name: Build
        run: dotnet build ${{ env.CSPROJ }} --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal