name: Publish

on: [push]

env: 
  CSPROJ: CodeGenerator/CodeGenerator.csproj
  GITHUB_NUGET_SOURCE_URL: https://nuget.pkg.github.com/drillfreak100/index.json

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Install dependencies
        run: dotnet restore ${{ env.CSPROJ }}

      - name: Build
        run: dotnet build ${{ env.CSPROJ }} --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack ${{ env.CSPROJ }} --no-restore --no-build --configuration Release

      - name: Publish to GitHub Packages
        run: dotnet nuget push CodeGenerator/bin/Release/*.nupkg -k  -s ${{ env.GITHUB_NUGET_SOURCE_URL }}