name: Publish
on: [push]
jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
          source-url: https://nuget.pkg.github.com/<owner>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Install dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Build
        run: dotnet build --configuration Release --no-restore CodeGenerator/CodeGenerator.csproj

      - name: Create the package
        run: dotnet pack --configuration Release CodeGenerator/CodeGenerator.csproj

      - name: Publish the package to GPR
        run: dotnet nuget push CodeGenerator/bin/Release/*.nupkg