name: Publish
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/drillfreak100/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release CodeGenerator
      - name: Create the package
        run: dotnet pack --configuration Release CodeGenerator
      - name: Publish the package to GPR
        run: dotnet nuget push CodeGenerator/bin/Release/*.nupkg